language:
- cpp

os:
- linux
- osx

compiler:
- g++
- clang

install:
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y ghostscript groff valgrind ; else brew install ghostscript; brew install valgrind ; fi

script:
- ./autogen.sh
- ./configure
- make
